[package]
name = "srtm"
version = "0.2.1"
edition = "2021"
authors = [
  "Jochen Görtler <web@goertler.email>",
  "Jeromos Kovács <iitsnotme214@proton.me>",
]

description = "Reads elevation data from `.hgt` files in Rust."
repository = "https://github.com/grtlr/srtm.git"

keywords = ["srtm", "hgt", "elevation-data"]
categories = ["science"]
license = "BSD-3-Clause"

[dependencies]
byteorder = "1.5.0"
