[package]
name = "srtm"
version = "0.1.1"
edition = "2021"
authors = ["Jochen Görtler <web@goertler.email>"]

description = "Reads elevation data from `.hgt` files in Rust."
repository = "https://github.com/grtlr/srtm.git"
readme = "README.md"

keywords = ["srtm", "hgt", "elevation-data", "srtm"]
categories = ["science"]
license = "BSD-3-Clause"

[dependencies]
byteorder = "1.5.0"
